// Code generated by protoc-gen-gogo.
// source: flamegraphpb.proto
// DO NOT EDIT!

/*
	Package flamegraphpb is a generated protocol buffer package.

	It is generated from these files:
		flamegraphpb.proto

	It has these top-level messages:
		ProtocolVersionResponse
		FlameGraphNode
		MetricStats
		MultiMetricStats
*/
package flamegraphpb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ProtocolVersionResponse struct {
	Version int64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (m *ProtocolVersionResponse) Reset()         { *m = ProtocolVersionResponse{} }
func (m *ProtocolVersionResponse) String() string { return proto.CompactTextString(m) }
func (*ProtocolVersionResponse) ProtoMessage()    {}
func (*ProtocolVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptorFlamegraphpb, []int{0}
}

func (m *ProtocolVersionResponse) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type FlameGraphNode struct {
	Id          uint64            `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Cluster     string            `protobuf:"bytes,2,opt,name=Cluster,proto3" json:"Cluster,omitempty"`
	Name        string            `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Total       uint64            `protobuf:"varint,4,opt,name=Total,proto3" json:"Total,omitempty"`
	Value       uint64            `protobuf:"varint,5,opt,name=Value,proto3" json:"Value,omitempty"`
	ModTime     int64             `protobuf:"varint,6,opt,name=ModTime,proto3" json:"ModTime,omitempty"`
	RdTime      int64             `protobuf:"varint,7,opt,name=RdTime,proto3" json:"RdTime,omitempty"`
	ATime       int64             `protobuf:"varint,8,opt,name=ATime,proto3" json:"ATime,omitempty"`
	Count       uint64            `protobuf:"varint,9,opt,name=Count,proto3" json:"Count,omitempty"`
	Children    []*FlameGraphNode `protobuf:"bytes,10,rep,name=Children" json:"Children,omitempty"`
	ChildrenIds []uint64          `protobuf:"varint,11,rep,packed,name=ChildrenIds" json:"ChildrenIds,omitempty"`
	ParentID    uint64            `protobuf:"varint,12,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
}

func (m *FlameGraphNode) Reset()                    { *m = FlameGraphNode{} }
func (m *FlameGraphNode) String() string            { return proto.CompactTextString(m) }
func (*FlameGraphNode) ProtoMessage()               {}
func (*FlameGraphNode) Descriptor() ([]byte, []int) { return fileDescriptorFlamegraphpb, []int{1} }

func (m *FlameGraphNode) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FlameGraphNode) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *FlameGraphNode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FlameGraphNode) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *FlameGraphNode) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *FlameGraphNode) GetModTime() int64 {
	if m != nil {
		return m.ModTime
	}
	return 0
}

func (m *FlameGraphNode) GetRdTime() int64 {
	if m != nil {
		return m.RdTime
	}
	return 0
}

func (m *FlameGraphNode) GetATime() int64 {
	if m != nil {
		return m.ATime
	}
	return 0
}

func (m *FlameGraphNode) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *FlameGraphNode) GetChildren() []*FlameGraphNode {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *FlameGraphNode) GetChildrenIds() []uint64 {
	if m != nil {
		return m.ChildrenIds
	}
	return nil
}

func (m *FlameGraphNode) GetParentID() uint64 {
	if m != nil {
		return m.ParentID
	}
	return 0
}

type MetricStats struct {
	Cluster string `protobuf:"bytes,1,opt,name=Cluster,proto3" json:"Cluster,omitempty"`
	Path    string `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
	ModTime int64  `protobuf:"varint,3,opt,name=ModTime,proto3" json:"ModTime,omitempty"`
	ATime   int64  `protobuf:"varint,4,opt,name=ATime,proto3" json:"ATime,omitempty"`
	RdTime  int64  `protobuf:"varint,5,opt,name=RdTime,proto3" json:"RdTime,omitempty"`
	Size_   int64  `protobuf:"varint,6,opt,name=Size,proto3" json:"Size,omitempty"`
	Count   int64  `protobuf:"varint,7,opt,name=Count,proto3" json:"Count,omitempty"`
}

func (m *MetricStats) Reset()                    { *m = MetricStats{} }
func (m *MetricStats) String() string            { return proto.CompactTextString(m) }
func (*MetricStats) ProtoMessage()               {}
func (*MetricStats) Descriptor() ([]byte, []int) { return fileDescriptorFlamegraphpb, []int{2} }

func (m *MetricStats) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *MetricStats) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *MetricStats) GetModTime() int64 {
	if m != nil {
		return m.ModTime
	}
	return 0
}

func (m *MetricStats) GetATime() int64 {
	if m != nil {
		return m.ATime
	}
	return 0
}

func (m *MetricStats) GetRdTime() int64 {
	if m != nil {
		return m.RdTime
	}
	return 0
}

func (m *MetricStats) GetSize_() int64 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *MetricStats) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type MultiMetricStats struct {
	Metrics []MetricStats `protobuf:"bytes,1,rep,name=metrics" json:"metrics"`
}

func (m *MultiMetricStats) Reset()                    { *m = MultiMetricStats{} }
func (m *MultiMetricStats) String() string            { return proto.CompactTextString(m) }
func (*MultiMetricStats) ProtoMessage()               {}
func (*MultiMetricStats) Descriptor() ([]byte, []int) { return fileDescriptorFlamegraphpb, []int{3} }

func (m *MultiMetricStats) GetMetrics() []MetricStats {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtocolVersionResponse)(nil), "flamegraphpb.ProtocolVersionResponse")
	proto.RegisterType((*FlameGraphNode)(nil), "flamegraphpb.FlameGraphNode")
	proto.RegisterType((*MetricStats)(nil), "flamegraphpb.MetricStats")
	proto.RegisterType((*MultiMetricStats)(nil), "flamegraphpb.MultiMetricStats")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FlamegraphV1 service

type FlamegraphV1Client interface {
	GetVersion(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*ProtocolVersionResponse, error)
	SendFlamegraph(ctx context.Context, in *FlameGraphNode, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	SendMetricsStats(ctx context.Context, in *MultiMetricStats, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type flamegraphV1Client struct {
	cc *grpc.ClientConn
}

func NewFlamegraphV1Client(cc *grpc.ClientConn) FlamegraphV1Client {
	return &flamegraphV1Client{cc}
}

func (c *flamegraphV1Client) GetVersion(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*ProtocolVersionResponse, error) {
	out := new(ProtocolVersionResponse)
	err := grpc.Invoke(ctx, "/flamegraphpb.FlamegraphV1/GetVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flamegraphV1Client) SendFlamegraph(ctx context.Context, in *FlameGraphNode, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/flamegraphpb.FlamegraphV1/SendFlamegraph", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flamegraphV1Client) SendMetricsStats(ctx context.Context, in *MultiMetricStats, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/flamegraphpb.FlamegraphV1/SendMetricsStats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FlamegraphV1 service

type FlamegraphV1Server interface {
	GetVersion(context.Context, *google_protobuf1.Empty) (*ProtocolVersionResponse, error)
	SendFlamegraph(context.Context, *FlameGraphNode) (*google_protobuf1.Empty, error)
	SendMetricsStats(context.Context, *MultiMetricStats) (*google_protobuf1.Empty, error)
}

func RegisterFlamegraphV1Server(s *grpc.Server, srv FlamegraphV1Server) {
	s.RegisterService(&_FlamegraphV1_serviceDesc, srv)
}

func _FlamegraphV1_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlamegraphV1Server).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flamegraphpb.FlamegraphV1/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlamegraphV1Server).GetVersion(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlamegraphV1_SendFlamegraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlameGraphNode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlamegraphV1Server).SendFlamegraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flamegraphpb.FlamegraphV1/SendFlamegraph",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlamegraphV1Server).SendFlamegraph(ctx, req.(*FlameGraphNode))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlamegraphV1_SendMetricsStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiMetricStats)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlamegraphV1Server).SendMetricsStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flamegraphpb.FlamegraphV1/SendMetricsStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlamegraphV1Server).SendMetricsStats(ctx, req.(*MultiMetricStats))
	}
	return interceptor(ctx, in, info, handler)
}

var _FlamegraphV1_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flamegraphpb.FlamegraphV1",
	HandlerType: (*FlamegraphV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _FlamegraphV1_GetVersion_Handler,
		},
		{
			MethodName: "SendFlamegraph",
			Handler:    _FlamegraphV1_SendFlamegraph_Handler,
		},
		{
			MethodName: "SendMetricsStats",
			Handler:    _FlamegraphV1_SendMetricsStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flamegraphpb.proto",
}

func (m *ProtocolVersionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProtocolVersionResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Version != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintFlamegraphpb(dAtA, i, uint64(m.Version))
	}
	return i, nil
}

func (m *FlameGraphNode) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FlameGraphNode) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintFlamegraphpb(dAtA, i, uint64(m.Id))
	}
	if len(m.Cluster) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintFlamegraphpb(dAtA, i, uint64(len(m.Cluster)))
		i += copy(dAtA[i:], m.Cluster)
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintFlamegraphpb(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if m.Total != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintFlamegraphpb(dAtA, i, uint64(m.Total))
	}
	if m.Value != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintFlamegraphpb(dAtA, i, uint64(m.Value))
	}
	if m.ModTime != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintFlamegraphpb(dAtA, i, uint64(m.ModTime))
	}
	if m.RdTime != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintFlamegraphpb(dAtA, i, uint64(m.RdTime))
	}
	if m.ATime != 0 {
		dAtA[i] = 0x40
		i++
		i = encodeVarintFlamegraphpb(dAtA, i, uint64(m.ATime))
	}
	if m.Count != 0 {
		dAtA[i] = 0x48
		i++
		i = encodeVarintFlamegraphpb(dAtA, i, uint64(m.Count))
	}
	if len(m.Children) > 0 {
		for _, msg := range m.Children {
			dAtA[i] = 0x52
			i++
			i = encodeVarintFlamegraphpb(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.ChildrenIds) > 0 {
		dAtA2 := make([]byte, len(m.ChildrenIds)*10)
		var j1 int
		for _, num := range m.ChildrenIds {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		dAtA[i] = 0x5a
		i++
		i = encodeVarintFlamegraphpb(dAtA, i, uint64(j1))
		i += copy(dAtA[i:], dAtA2[:j1])
	}
	if m.ParentID != 0 {
		dAtA[i] = 0x60
		i++
		i = encodeVarintFlamegraphpb(dAtA, i, uint64(m.ParentID))
	}
	return i, nil
}

func (m *MetricStats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MetricStats) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Cluster) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintFlamegraphpb(dAtA, i, uint64(len(m.Cluster)))
		i += copy(dAtA[i:], m.Cluster)
	}
	if len(m.Path) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintFlamegraphpb(dAtA, i, uint64(len(m.Path)))
		i += copy(dAtA[i:], m.Path)
	}
	if m.ModTime != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintFlamegraphpb(dAtA, i, uint64(m.ModTime))
	}
	if m.ATime != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintFlamegraphpb(dAtA, i, uint64(m.ATime))
	}
	if m.RdTime != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintFlamegraphpb(dAtA, i, uint64(m.RdTime))
	}
	if m.Size_ != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintFlamegraphpb(dAtA, i, uint64(m.Size_))
	}
	if m.Count != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintFlamegraphpb(dAtA, i, uint64(m.Count))
	}
	return i, nil
}

func (m *MultiMetricStats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MultiMetricStats) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Metrics) > 0 {
		for _, msg := range m.Metrics {
			dAtA[i] = 0xa
			i++
			i = encodeVarintFlamegraphpb(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func encodeFixed64Flamegraphpb(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Flamegraphpb(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintFlamegraphpb(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ProtocolVersionResponse) Size() (n int) {
	var l int
	_ = l
	if m.Version != 0 {
		n += 1 + sovFlamegraphpb(uint64(m.Version))
	}
	return n
}

func (m *FlameGraphNode) Size() (n int) {
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovFlamegraphpb(uint64(m.Id))
	}
	l = len(m.Cluster)
	if l > 0 {
		n += 1 + l + sovFlamegraphpb(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovFlamegraphpb(uint64(l))
	}
	if m.Total != 0 {
		n += 1 + sovFlamegraphpb(uint64(m.Total))
	}
	if m.Value != 0 {
		n += 1 + sovFlamegraphpb(uint64(m.Value))
	}
	if m.ModTime != 0 {
		n += 1 + sovFlamegraphpb(uint64(m.ModTime))
	}
	if m.RdTime != 0 {
		n += 1 + sovFlamegraphpb(uint64(m.RdTime))
	}
	if m.ATime != 0 {
		n += 1 + sovFlamegraphpb(uint64(m.ATime))
	}
	if m.Count != 0 {
		n += 1 + sovFlamegraphpb(uint64(m.Count))
	}
	if len(m.Children) > 0 {
		for _, e := range m.Children {
			l = e.Size()
			n += 1 + l + sovFlamegraphpb(uint64(l))
		}
	}
	if len(m.ChildrenIds) > 0 {
		l = 0
		for _, e := range m.ChildrenIds {
			l += sovFlamegraphpb(uint64(e))
		}
		n += 1 + sovFlamegraphpb(uint64(l)) + l
	}
	if m.ParentID != 0 {
		n += 1 + sovFlamegraphpb(uint64(m.ParentID))
	}
	return n
}

func (m *MetricStats) Size() (n int) {
	var l int
	_ = l
	l = len(m.Cluster)
	if l > 0 {
		n += 1 + l + sovFlamegraphpb(uint64(l))
	}
	l = len(m.Path)
	if l > 0 {
		n += 1 + l + sovFlamegraphpb(uint64(l))
	}
	if m.ModTime != 0 {
		n += 1 + sovFlamegraphpb(uint64(m.ModTime))
	}
	if m.ATime != 0 {
		n += 1 + sovFlamegraphpb(uint64(m.ATime))
	}
	if m.RdTime != 0 {
		n += 1 + sovFlamegraphpb(uint64(m.RdTime))
	}
	if m.Size_ != 0 {
		n += 1 + sovFlamegraphpb(uint64(m.Size_))
	}
	if m.Count != 0 {
		n += 1 + sovFlamegraphpb(uint64(m.Count))
	}
	return n
}

func (m *MultiMetricStats) Size() (n int) {
	var l int
	_ = l
	if len(m.Metrics) > 0 {
		for _, e := range m.Metrics {
			l = e.Size()
			n += 1 + l + sovFlamegraphpb(uint64(l))
		}
	}
	return n
}

func sovFlamegraphpb(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozFlamegraphpb(x uint64) (n int) {
	return sovFlamegraphpb(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ProtocolVersionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFlamegraphpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProtocolVersionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProtocolVersionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlamegraphpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFlamegraphpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFlamegraphpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FlameGraphNode) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFlamegraphpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FlameGraphNode: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FlameGraphNode: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlamegraphpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cluster", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlamegraphpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFlamegraphpb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cluster = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlamegraphpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFlamegraphpb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlamegraphpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			m.Value = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlamegraphpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Value |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModTime", wireType)
			}
			m.ModTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlamegraphpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ModTime |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RdTime", wireType)
			}
			m.RdTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlamegraphpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RdTime |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ATime", wireType)
			}
			m.ATime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlamegraphpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ATime |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlamegraphpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Children", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlamegraphpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFlamegraphpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Children = append(m.Children, &FlameGraphNode{})
			if err := m.Children[len(m.Children)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowFlamegraphpb
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ChildrenIds = append(m.ChildrenIds, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowFlamegraphpb
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthFlamegraphpb
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowFlamegraphpb
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ChildrenIds = append(m.ChildrenIds, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ChildrenIds", wireType)
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParentID", wireType)
			}
			m.ParentID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlamegraphpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ParentID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFlamegraphpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFlamegraphpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetricStats) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFlamegraphpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetricStats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetricStats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cluster", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlamegraphpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFlamegraphpb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cluster = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlamegraphpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFlamegraphpb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Path = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModTime", wireType)
			}
			m.ModTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlamegraphpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ModTime |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ATime", wireType)
			}
			m.ATime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlamegraphpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ATime |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RdTime", wireType)
			}
			m.RdTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlamegraphpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RdTime |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Size_", wireType)
			}
			m.Size_ = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlamegraphpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Size_ |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlamegraphpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFlamegraphpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFlamegraphpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MultiMetricStats) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFlamegraphpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MultiMetricStats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MultiMetricStats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metrics", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlamegraphpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFlamegraphpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metrics = append(m.Metrics, MetricStats{})
			if err := m.Metrics[len(m.Metrics)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFlamegraphpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFlamegraphpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFlamegraphpb(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFlamegraphpb
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFlamegraphpb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFlamegraphpb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthFlamegraphpb
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowFlamegraphpb
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipFlamegraphpb(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthFlamegraphpb = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFlamegraphpb   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("flamegraphpb.proto", fileDescriptorFlamegraphpb) }

var fileDescriptorFlamegraphpb = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xce, 0x26, 0xce, 0x4f, 0x27, 0x51, 0x54, 0xad, 0x50, 0x59, 0x02, 0x0a, 0x96, 0x25, 0xa4,
	0x5c, 0x70, 0x45, 0x7b, 0x81, 0x23, 0x0d, 0xb4, 0x44, 0xc2, 0x55, 0xe4, 0x54, 0xb9, 0x3b, 0xf1,
	0xd6, 0xb1, 0x64, 0x7b, 0x2d, 0x7b, 0x8d, 0x04, 0xef, 0xc4, 0x7b, 0xf4, 0xd8, 0x27, 0x40, 0x28,
	0xef, 0xc0, 0x1d, 0xed, 0x6c, 0x9c, 0xd8, 0x45, 0xe1, 0x36, 0xdf, 0x37, 0xdf, 0xce, 0xcf, 0xb7,
	0x03, 0xf4, 0x3e, 0xf2, 0x62, 0x1e, 0x64, 0x5e, 0xba, 0x49, 0x57, 0x76, 0x9a, 0x09, 0x29, 0xe8,
	0xa0, 0xca, 0x8d, 0xde, 0x06, 0xa1, 0xdc, 0x14, 0x2b, 0x7b, 0x2d, 0xe2, 0xf3, 0x40, 0x04, 0xe2,
	0x1c, 0x45, 0xab, 0xe2, 0x1e, 0x11, 0x02, 0x8c, 0xf4, 0xe3, 0xd1, 0xcb, 0x40, 0x88, 0x20, 0xe2,
	0x07, 0x15, 0x8f, 0x53, 0xf9, 0x5d, 0x27, 0xad, 0x4b, 0x78, 0x3e, 0x57, 0xc1, 0x5a, 0x44, 0x4b,
	0x9e, 0xe5, 0xa1, 0x48, 0x5c, 0x9e, 0xa7, 0x22, 0xc9, 0x39, 0x65, 0xd0, 0xfd, 0xa6, 0x29, 0x46,
	0x4c, 0x32, 0x69, 0xb9, 0x25, 0xb4, 0x1e, 0x9b, 0x30, 0xbc, 0x56, 0x13, 0xdd, 0xa8, 0x89, 0x6e,
	0x85, 0xcf, 0xe9, 0x10, 0x9a, 0x33, 0x1f, 0x75, 0x86, 0xdb, 0x9c, 0xf9, 0xea, 0xf1, 0x34, 0x2a,
	0x72, 0xc9, 0x33, 0xd6, 0x34, 0xc9, 0xe4, 0xc4, 0x2d, 0x21, 0xa5, 0x60, 0xdc, 0x7a, 0x31, 0x67,
	0x2d, 0xa4, 0x31, 0xa6, 0xcf, 0xa0, 0x7d, 0x27, 0xa4, 0x17, 0x31, 0x03, 0x0b, 0x68, 0xa0, 0xd8,
	0xa5, 0x17, 0x15, 0x9c, 0xb5, 0x35, 0x8b, 0x40, 0x55, 0x76, 0x84, 0x7f, 0x17, 0xc6, 0x9c, 0x75,
	0xf4, 0x58, 0x3b, 0x48, 0xcf, 0xa0, 0xe3, 0xea, 0x44, 0x17, 0x13, 0x3b, 0xa4, 0xea, 0x7c, 0x44,
	0xba, 0x87, 0xb4, 0x06, 0x8a, 0x9d, 0x8a, 0x22, 0x91, 0xec, 0x44, 0x57, 0x47, 0x40, 0xdf, 0x43,
	0x6f, 0xba, 0x09, 0x23, 0x3f, 0xe3, 0x09, 0x03, 0xb3, 0x35, 0xe9, 0x5f, 0xbc, 0xb2, 0x6b, 0x1f,
	0x52, 0xdf, 0xdb, 0xdd, 0xab, 0xa9, 0x09, 0xfd, 0x32, 0x9e, 0xf9, 0x39, 0xeb, 0x9b, 0xad, 0x89,
	0xe1, 0x56, 0x29, 0x3a, 0x82, 0xde, 0xdc, 0xcb, 0x78, 0x22, 0x67, 0x9f, 0xd8, 0x00, 0x9b, 0xee,
	0xb1, 0xf5, 0x93, 0x40, 0xdf, 0xe1, 0x32, 0x0b, 0xd7, 0x0b, 0xe9, 0xc9, 0xbc, 0xea, 0x1f, 0xf9,
	0xc7, 0xbf, 0xb9, 0x27, 0x37, 0x3b, 0x5b, 0x31, 0xae, 0x7a, 0xd2, 0xaa, 0x7b, 0xb2, 0xdf, 0xdd,
	0xa8, 0xee, 0x7e, 0x70, 0xaa, 0x5d, 0x73, 0x8a, 0x82, 0xb1, 0x08, 0x7f, 0x94, 0xc6, 0x62, 0x7c,
	0xf0, 0x49, 0x9b, 0xaa, 0x81, 0xe5, 0xc0, 0xa9, 0x53, 0x44, 0x32, 0xac, 0xce, 0xfc, 0x01, 0xba,
	0x31, 0xc2, 0x9c, 0x11, 0xb4, 0xee, 0x45, 0xdd, 0xba, 0x8a, 0xf6, 0xca, 0x78, 0xf8, 0xf5, 0xba,
	0xe1, 0x96, 0xfa, 0x8b, 0x3f, 0x04, 0x06, 0xd7, 0x7b, 0xed, 0xf2, 0x1d, 0x75, 0x00, 0x6e, 0xb8,
	0xdc, 0x9d, 0x24, 0x3d, 0xb3, 0xf5, 0x0d, 0xdb, 0xe5, 0x0d, 0xdb, 0x9f, 0xd5, 0x0d, 0x8f, 0xde,
	0xd4, 0x1b, 0x1c, 0xb9, 0x64, 0xab, 0x41, 0xbf, 0xc0, 0x70, 0xc1, 0x13, 0xff, 0xd0, 0x82, 0xfe,
	0xf7, 0x5b, 0x47, 0x47, 0x1a, 0x5a, 0x0d, 0xfa, 0x15, 0x4e, 0x55, 0x25, 0xbd, 0x4b, 0xae, 0x17,
	0x1f, 0x3f, 0xd9, 0xf3, 0x89, 0x31, 0xc7, 0xab, 0x5d, 0x0d, 0x1e, 0xb6, 0x63, 0xf2, 0xb8, 0x1d,
	0x93, 0xdf, 0xdb, 0x31, 0x59, 0x75, 0x30, 0x7f, 0xf9, 0x37, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xd3,
	0x2e, 0x9a, 0x03, 0x04, 0x00, 0x00,
}
